interface INode {
  id: string
  name?: string
  label?: {
    show?: boolean
  }
}
interface ILink {
  source: string
  target: string
}
export const data: { nodes: INode[]; links: ILink[] } = {
  nodes: [
    { id: 'integral' },
    { id: 'critical' },
    { id: 'crucial' },
    { id: 'essential' },
    { id: 'necessary' },
    { id: 'required' },
    { id: 'indispensable' },
    { id: 'basic' },
    { id: 'elemental' },
    { id: 'elementary' },
    { id: 'fundamental' },
    { id: 'introductory' },
    { id: 'paramount' },
    { id: 'vital' },
    { id: 'important' },
    { id: 'invigorating' },
    { id: 'refreshing' },
    { id: 'rejuvenating' },
    { id: 'restorative' },
    { id: 'restoring' },
    { id: 'hardy' },
    { id: 'hearty' },
    { id: 'robust' },
    { id: 'strong' },
    { id: 'vigorous' },
    { id: 'deprecating' },
    { id: 'belittling' },
    { id: 'degrading' },
    { id: 'demeaning' },
    { id: 'derogative' },
    { id: 'diminishing' },
    { id: 'binding' },
    { id: 'compulsory' },
    { id: 'major' },
    { id: 'foremost' },
    { id: 'principal' },
    { id: 'prominent' },
    { id: 'rudimentary' },
    { id: 'bare' },
    { id: 'plain' },
    { id: 'raw' },
    { id: 'crude' },
    { id: 'primal' },
    { id: 'entire' },
    { id: 'absolute' },
    { id: 'real' },
    { id: 'total' },
    { id: 'actual' },
    { id: 'virtual' },
    { id: 'implied' },
    { id: 'initial' },
    { id: 'prefatory' },
    { id: 'preparatory' },
    { id: 'preliminary' },
    { id: 'preceding' },
    { id: 'consequential' },
    { id: 'influential' },
    { id: 'meaningful' },
    { id: 'momentous' },
    { id: 'significant' },
    { id: 'substantial' },
    { id: 'enlivening' },
    { id: 'revitalizing' },
    { id: 'animating' },
    { id: 'livening' },
    { id: 'vitalizing' },
    { id: 'tonic' },
    { id: 'beneficial' },
    { id: 'healthy' },
    { id: 'healthful' },
    { id: 'wholesome' },
    { id: 'healing' },
    { id: 'remedial' },
    { id: 'medicinal' },
    { id: 'therapeutic' },
    { id: 'fixing' },
    { id: 'patching' },
    { id: 'repairing' },
    { id: 'mending' },
    { id: 'correcting' },
    { id: 'reforming' },
    { id: 'habilitating' },
    { id: 'converting' },
    { id: 'reawakening' },
    { id: 'rekindling' },
    { id: 'reviving' },
    { id: 'resurrecting' },
    { id: 'reanimating' },
    { id: 'rugged' },
    { id: 'bulky' },
    { id: 'husky' },
    { id: 'sturdy' },
    { id: 'beefy' },
    { id: 'wholehearted' },
    { id: 'concentrated' },
    { id: 'full' },
    { id: 'potent' },
    { id: 'rich' },
    { id: 'full-bodied' },
    { id: 'powerful' },
    { id: 'mighty' },
    { id: 'muscular' },
    { id: 'brawny' },
    { id: 'active' },
    { id: 'animated' },
    { id: 'bouncy' },
    { id: 'energetic' },
    { id: 'energized' },
    { id: 'emotional' },
    { id: 'emotive' },
    { id: 'fervid' },
    { id: 'fiery' },
    { id: 'impassioned' },
    { id: 'criticizing' },
    { id: 'disparaging' },
    { id: 'faulting' },
    { id: 'knocking' },
    { id: 'deriding' },
    { id: 'trashing' },
    { id: 'denigrating' },
    { id: 'derogatory' },
    { id: 'delining' },
    { id: 'decreasing' },
    { id: 'dwindling' },
    { id: 'ebbing' },
    { id: 'lessening' },
    { id: 'paring' },
    { id: 'reducing' },
    { id: 'acute' },
    { id: 'imperative' },
    { id: 'mandatory' },
    { id: 'obligatory' },
    { id: 'demanded' },
    { id: 'needed' },
    { id: 'directed' },
    { id: 'instructed' },
    { id: 'mandated' },
    // { id: '' },
  ],
  links: [
    { source: 'integral', target: 'critical' },
    { source: 'integral', target: 'crucial' },
    { source: 'integral', target: 'essential' },
    { source: 'integral', target: 'necessary' },
    { source: 'integral', target: 'required' },
    { source: 'essential', target: 'critical' },
    { source: 'essential', target: 'crucial' },
    { source: 'essential', target: 'indispensable' },
    { source: 'essential', target: 'integral' },
    { source: 'essential', target: 'necessary' },
    { source: 'essential', target: 'basic' },
    { source: 'essential', target: 'elemental' },
    { source: 'essential', target: 'elementary' },
    { source: 'essential', target: 'fundamental' },
    { source: 'essential', target: 'introductory' },
    { source: 'essential', target: 'paramount' },
    { source: 'essential', target: 'vital' },
    { source: 'essential', target: 'important' },
    { source: 'vital', target: 'invigorating' },
    { source: 'vital', target: 'refreshing' },
    { source: 'vital', target: 'rejuvenating' },
    { source: 'vital', target: 'restorative' },
    { source: 'vital', target: 'restoring' },
    { source: 'vital', target: 'hardy' },
    { source: 'vital', target: 'hearty' },
    { source: 'vital', target: 'robust' },
    { source: 'vital', target: 'strong' },
    { source: 'vital', target: 'vigorous' },
    { source: 'vital', target: 'critical' },
    { source: 'vital', target: 'crucial' },
    { source: 'vital', target: 'indispensable' },
    { source: 'vital', target: 'integral' },
    { source: 'vital', target: 'necessary' },
    { source: 'critical', target: 'deprecating' },
    { source: 'critical', target: 'belittling' },
    { source: 'critical', target: 'degrading' },
    { source: 'critical', target: 'demeaning' },
    { source: 'critical', target: 'derogative' },
    { source: 'critical', target: 'diminishing' },
    { source: 'critical', target: 'essential' },
    { source: 'critical', target: 'crucial' },
    { source: 'critical', target: 'indispensable' },
    { source: 'critical', target: 'integral' },
    { source: 'critical', target: 'necessary' },
    { source: 'crucial', target: 'critical' },
    { source: 'crucial', target: 'essential' },
    { source: 'crucial', target: 'paramount' },
    { source: 'crucial', target: 'vital' },
    { source: 'crucial', target: 'important' },
    { source: 'crucial', target: 'critical' },
    { source: 'crucial', target: 'essential' },
    { source: 'crucial', target: 'indispensable' },
    { source: 'crucial', target: 'integral' },
    { source: 'crucial', target: 'necessary' },
    { source: 'crucial', target: 'binding' },
    { source: 'crucial', target: 'compulsory' },
    { source: 'crucial', target: 'critical' },
    { source: 'paramount', target: 'central' },
    { source: 'paramount', target: 'major' },
    { source: 'paramount', target: 'foremost' },
    { source: 'paramount', target: 'principal' },
    { source: 'paramount', target: 'prominent' },
    { source: 'paramount', target: 'critical' },
    { source: 'paramount', target: 'essential' },
    { source: 'paramount', target: 'crucial' },
    { source: 'paramount', target: 'vital' },
    { source: 'paramount', target: 'important' },
    { source: 'necessary', target: 'critical' },
    { source: 'necessary', target: 'crucial' },
    { source: 'necessary', target: 'indispensable' },
    { source: 'necessary', target: 'integral' },
    { source: 'necessary', target: 'essential' },
    { source: 'indispensable', target: 'critical' },
    { source: 'indispensable', target: 'crucial' },
    { source: 'indispensable', target: 'essential' },
    { source: 'indispensable', target: 'integral' },
    { source: 'indispensable', target: 'necessary' },
    { source: 'basic', target: 'elemental' },
    { source: 'basic', target: 'essential' },
    { source: 'basic', target: 'fundamental' },
    { source: 'basic', target: 'introductory' },
    { source: 'basic', target: 'rudimentary' },
    { source: 'basic', target: 'bare' },
    { source: 'basic', target: 'plain' },
    { source: 'basic', target: 'raw' },
    { source: 'elemental', target: 'basic' },
    { source: 'elemental', target: 'elementary' },
    { source: 'elemental', target: 'essential' },
    { source: 'elemental', target: 'fundamental' },
    { source: 'elemental', target: 'introductory' },
    { source: 'elementary', target: 'elemental' },
    { source: 'elementary', target: 'crude' },
    { source: 'elementary', target: 'primal' },
    { source: 'fundamental', target: 'entire' },
    { source: 'fundamental', target: 'absolute' },
    { source: 'fundamental', target: 'indisputable' },
    { source: 'fundamental', target: 'real' },
    { source: 'fundamental', target: 'total' },
    { source: 'fundamental', target: 'basic' },
    { source: 'fundamental', target: 'elemental' },
    { source: 'fundamental', target: 'essential' },
    { source: 'fundamental', target: 'introductory' },
    { source: 'fundamental', target: 'rudimentary' },
    { source: 'fundamental', target: 'actual' },
    { source: 'fundamental', target: 'basic' },
    { source: 'fundamental', target: 'virtual' },
    { source: 'fundamental', target: 'implied' },
    { source: 'introductory', target: 'elemental' },
    { source: 'introductory', target: 'essential' },
    { source: 'introductory', target: 'elementary' },
    { source: 'introductory', target: 'rudimentary' },
    { source: 'introductory', target: 'initial' },
    { source: 'introductory', target: 'prefatory' },
    { source: 'introductory', target: 'preparatory' },
    { source: 'introductory', target: 'preliminary' },
    { source: 'introductory', target: 'preceding' },
    { source: 'important', target: 'consequential' },
    { source: 'important', target: 'influential' },
    { source: 'important', target: 'meaningful' },
    { source: 'important', target: 'momentous' },
    { source: 'important', target: 'significant' },
    { source: 'important', target: 'consequential' },
    { source: 'important', target: 'influential' },
    { source: 'important', target: 'substantial' },
    { source: 'important', target: 'critical' },
    { source: 'important', target: 'essential' },
    { source: 'important', target: 'paramount' },
    { source: 'important', target: 'vital' },
    { source: 'important', target: 'necessary' },
    { source: 'invigorating', target: 'enlivening' },
    { source: 'invigorating', target: 'revitalizing' },
    { source: 'invigorating', target: 'animating' },
    { source: 'invigorating', target: 'livening' },
    { source: 'invigorating', target: 'vitalizing' },
    { source: 'refreshing', target: 'invigorating' },
    { source: 'refreshing', target: 'tonic' },
    { source: 'refreshing', target: 'rejuvenating' },
    { source: 'refreshing', target: 'restorative' },
    { source: 'refreshing', target: 'restoring' },
    { source: 'restorative', target: 'beneficial' },
    { source: 'restorative', target: 'healthy' },
    { source: 'restorative', target: 'healthful' },
    { source: 'restorative', target: 'wholesome' },
    { source: 'restorative', target: 'invigorating' },
    { source: 'restorative', target: 'refreshing' },
    { source: 'restorative', target: 'rejuvenating' },
    { source: 'restorative', target: 'tonic' },
    { source: 'restorative', target: 'restoring' },
    { source: 'restorative', target: 'healing' },
    { source: 'restorative', target: 'remedial' },
    { source: 'restorative', target: 'medicinal' },
    { source: 'restorative', target: 'restoring' },
    { source: 'restorative', target: 'therapeutic' },
    { source: 'restoring', target: 'fixing' },
    { source: 'restoring', target: 'patching' },
    { source: 'restoring', target: 'repairing' },
    { source: 'restoring', target: 'mending' },
    { source: 'restoring', target: 'correcting' },
    { source: 'restoring', target: 'reforming' },
    { source: 'restoring', target: 'habilitating' },
    { source: 'restoring', target: 'converting' },
    { source: 'restoring', target: 'reawakening' },
    { source: 'restoring', target: 'rekindling' },
    { source: 'restoring', target: 'reviving' },
    { source: 'restoring', target: 'resurrecting' },
    { source: 'restoring', target: 'reanimating' },
    { source: 'hardy', target: 'rugged' },
    { source: 'hardy', target: 'vigorous' },
    { source: 'hardy', target: 'hearty' },
    { source: 'hardy', target: 'robust' },
    { source: 'hardy', target: 'vital' },
    { source: 'hardy', target: 'bulky' },
    { source: 'hardy', target: 'husky' },
    { source: 'hardy', target: 'sturdy' },
    { source: 'hardy', target: 'beefy' },
    { source: 'hearty', target: 'wholehearted' },
    { source: 'hearty', target: 'hardy' },
    { source: 'hearty', target: 'vigorous' },
    { source: 'hearty', target: 'robust' },
    { source: 'hearty', target: 'strong' },
    { source: 'hearty', target: 'vital' },
    { source: 'robust', target: 'hardy' },
    { source: 'robust', target: 'vigorous' },
    { source: 'robust', target: 'strong' },
    { source: 'robust', target: 'vital' },
    { source: 'robust', target: 'concentrated' },
    { source: 'robust', target: 'full' },
    { source: 'robust', target: 'potent' },
    { source: 'robust', target: 'rich' },
    { source: 'robust', target: 'full-bodied' },
    { source: 'robust', target: 'potent' },
    { source: 'robust', target: 'powerful' },
    { source: 'robust', target: 'mighty' },
    { source: 'robust', target: 'rugged' },
    { source: 'strong', target: 'muscular' },
    { source: 'strong', target: 'powerful' },
    { source: 'strong', target: 'robust' },
    { source: 'strong', target: 'vigorous' },
    { source: 'strong', target: 'healthy' },
    { source: 'strong', target: 'vital' },
    { source: 'strong', target: 'brawny' },
    { source: 'vigorous', target: 'hardy' },
    { source: 'vigorous', target: 'hearty' },
    { source: 'vigorous', target: 'robust' },
    { source: 'vigorous', target: 'strong' },
    { source: 'vigorous', target: 'vital' },
    { source: 'vigorous', target: 'active' },
    { source: 'vigorous', target: 'animated' },
    { source: 'vigorous', target: 'bouncy' },
    { source: 'vigorous', target: 'energetic' },
    { source: 'vigorous', target: 'energized' },
    { source: 'vigorous', target: 'emotional' },
    { source: 'vigorous', target: 'emotive' },
    { source: 'vigorous', target: 'fervid' },
    { source: 'vigorous', target: 'fiery' },
    { source: 'vigorous', target: 'impassioned' },
    { source: 'deprecating', target: 'belittling' },
    { source: 'deprecating', target: 'deprecating' },
    { source: 'belittling', target: 'criticizing' },
    { source: 'belittling', target: 'disparaging' },
    { source: 'belittling', target: 'faulting' },
    { source: 'belittling', target: 'knocking' },
    { source: 'belittling', target: 'criticizing' },
    { source: 'belittling', target: 'deriding' },
    { source: 'belittling', target: 'trashing' },
    { source: 'belittling', target: 'denigrating' },
    { source: 'belittling', target: 'disparaging' },
    { source: 'degrading', target: 'belittling' },
    { source: 'degrading', target: 'derogatory' },
    { source: 'degrading', target: 'demeaning' },
    { source: 'degrading', target: 'derogative' },
    { source: 'degrading', target: 'diminishing' },
    { source: 'demeaning', target: 'belittling' },
    { source: 'demeaning', target: 'degrading' },
    { source: 'demeaning', target: 'derogatory' },
    { source: 'demeaning', target: 'derogative' },
    { source: 'demeaning', target: 'diminishing' },
    { source: 'derogative', target: 'belittling' },
    { source: 'derogative', target: 'degrading' },
    { source: 'derogative', target: 'demeaning' },
    { source: 'derogative', target: 'derogatory' },
    { source: 'derogative', target: 'diminishing' },
    { source: 'diminishing', target: 'declining' },
    { source: 'diminishing', target: 'decreasing' },
    { source: 'diminishing', target: 'dwindling' },
    { source: 'diminishing', target: 'ebbing' },
    { source: 'diminishing', target: 'lessening' },
    { source: 'diminishing', target: 'paring' },
    { source: 'diminishing', target: 'lessening' },
    { source: 'diminishing', target: 'reducing' },
    { source: 'binding', target: 'acute' },
    { source: 'binding', target: 'imperative' },
    { source: 'binding', target: 'compulsory' },
    { source: 'binding', target: 'critical' },
    { source: 'binding', target: 'crucial' },
    { source: 'compulsory', target: 'mandatory' },
    { source: 'compulsory', target: 'obligatory' },
    { source: 'compulsory', target: 'required' },
    { source: 'compulsory', target: 'acute' },
    { source: 'compulsory', target: 'binding' },
    { source: 'compulsory', target: 'imperative' },
    { source: 'compulsory', target: 'critical' },
    { source: 'compulsory', target: 'crucial' },
    { source: 'required', target: 'demanded' },
    { source: 'required', target: 'needed' },
    { source: 'required', target: 'directed' },
    { source: 'required', target: 'instructed' },
    { source: 'required', target: 'mandated' },
    { source: 'indispensable', target: 'critical' },
    { source: 'indispensable', target: 'crucial' },
    { source: 'indispensable', target: 'essential' },
    { source: 'indispensable', target: 'integral' },
    { source: 'indispensable', target: 'necessary' },
    // { source: '', target: '' },
  ],
}
